# Generated by Django 6.0.3 on 2026-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('color', models.CharField(choices=[('#fff382', 'Yellow'), ('#ffc1cc', 'Pink'), ('#b2fab4', 'Green'), ('#b3e5fc', 'Blue')], default='#fff382', max_length=7)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
